### PR TITLE
Update software.md

### PR DESCRIPTION
**Pull request by khancyr**
Add grow partition step
remove -j8 from waf since waf will use by default as many processor as available
change to git submodule update --init --recursive

### CODE REVIEW

**Comment by khancyr** [comment]
by the way, the image proposed here isn't available anymore (and newer stuck in cylon mode for me... )

**Comment by mirkix** [comment]
@khancyr ok, will check that

**Comment by mirkix** [comment]
@khancyr Thanks!

**Comment by mirkix** [comment]
@khancyr The image should be back again.

**Pull request merged**
